name: Automerge
on:
  check_suite:
    types:
    - completed
jobs:
  worker:
    runs-on: ubuntu-20.04
    if: github.event.label.name == 'automerge'
    steps:
    - name: automerge
      uses: actions/github-script@0.2.0
      with:
        script: |
          github.pullRequests.merge({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number
          })
        github-token: ${{github.token}}
